// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcEIAjRhHo9nwrAmKXghzonEA8gvJH_Eo',
    appId: '1:376023713480:web:97ffe7a5b9d577c77407fd',
    messagingSenderId: '376023713480',
    projectId: 'authtutorial-9389a',
    authDomain: 'authtutorial-9389a.firebaseapp.com',
    storageBucket: 'authtutorial-9389a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIcr61NjekcLxPCwh4BtVtltJAAgb0eo',
    appId: '1:376023713480:android:b2c6f1d4b55f19e77407fd',
    messagingSenderId: '376023713480',
    projectId: 'authtutorial-9389a',
    storageBucket: 'authtutorial-9389a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMPfctktLKHwxOX1qDQfhARBKPwQrAsJg',
    appId: '1:376023713480:ios:43886cbe2772055b7407fd',
    messagingSenderId: '376023713480',
    projectId: 'authtutorial-9389a',
    storageBucket: 'authtutorial-9389a.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMPfctktLKHwxOX1qDQfhARBKPwQrAsJg',
    appId: '1:376023713480:ios:0ad16f9779a785157407fd',
    messagingSenderId: '376023713480',
    projectId: 'authtutorial-9389a',
    storageBucket: 'authtutorial-9389a.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
